Model already exists: ../sfd-main/src/cifar10/edm-cifar10-32x32-uncond-vp.pkl
Loading the pre-trained diffusion model from "../sfd-main/src/cifar10/edm-cifar10-32x32-uncond-vp.pkl"...
/home/zeus/miniconda3/envs/cloudspace/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py:4631: UserWarning: No device id is provided via `init_process_group` or `barrier `. Using the current device set by the user. 
  warnings.warn(  # warn only once
Total parameters in U-Net:      60396419
Setting up optimizer...
[rank0]: Traceback (most recent call last):
[rank0]:   File "/teamspace/studios/this_studio/sfd-main/train.py", line 155, in <module>
[rank0]:     main()
[rank0]:   File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.9/site-packages/click/core.py", line 1161, in __call__
[rank0]:     return self.main(*args, **kwargs)
[rank0]:   File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.9/site-packages/click/core.py", line 1082, in main
[rank0]:     rv = self.invoke(ctx)
[rank0]:   File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.9/site-packages/click/core.py", line 1443, in invoke
[rank0]:     return ctx.invoke(self.callback, **ctx.params)
[rank0]:   File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.9/site-packages/click/core.py", line 788, in invoke
[rank0]:     return __callback(*args, **kwargs)
[rank0]:   File "/teamspace/studios/this_studio/sfd-main/train.py", line 150, in main
[rank0]:     training_loop.training_loop(**c)
[rank0]:   File "/teamspace/studios/this_studio/sfd-main/training/training_loop.py", line 205, in training_loop
[rank0]:     loss_fn = dnnlib.util.construct_class_by_name(**loss_kwargs)
[rank0]:   File "/teamspace/studios/this_studio/sfd-main/dnnlib/util.py", line 302, in construct_class_by_name
[rank0]:     return call_func_by_name(*args, func_name=class_name, **kwargs)
[rank0]:   File "/teamspace/studios/this_studio/sfd-main/dnnlib/util.py", line 295, in call_func_by_name
[rank0]:     func_obj = get_obj_by_name(func_name)
[rank0]:   File "/teamspace/studios/this_studio/sfd-main/dnnlib/util.py", line 288, in get_obj_by_name
[rank0]:     module, obj_name = get_module_from_obj_name(name)
[rank0]:   File "/teamspace/studios/this_studio/sfd-main/dnnlib/util.py", line 259, in get_module_from_obj_name
[rank0]:     importlib.import_module(module_name) # may raise ImportError
[rank0]:   File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.9/importlib/__init__.py", line 127, in import_module
[rank0]:     return _bootstrap._gcd_import(name[level:], package, level)
[rank0]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
[rank0]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
[rank0]:   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
[rank0]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[rank0]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
[rank0]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
[rank0]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
[rank0]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
[rank0]:   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
[rank0]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
[rank0]:   File "/teamspace/studios/this_studio/sfd-main/training/loss.py", line 6, in <module>
[rank0]:     from piq import LPIPS
[rank0]: ModuleNotFoundError: No module named 'piq'
